name: Ubuntu SSH

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    env:
      GH_EMAIL: ${{ secrets.GH_EMAIL }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}

    steps:
      - uses: actions/checkout@main
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GH_EMAIL}
          git config --global user.name ${GH_NAME}
          git config --global credential.helper store
          echo "https://${GH_USERNAME}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      #- uses: rokibhasansagar/slimhub_actions@main
      - run: printenv | sort
      - name: SSH Keepalive
        run: |
          mkdir -p ~/.ssh
          cat << EOF > ~/.ssh/config
          Host *
              ServerAliveInterval 60
              StrictHostKeyChecking no
          Host github.com
              User git
              Port 22
              Hostname github.com
              TCPKeepAlive yes
              IdentitiesOnly yes
          EOF
      - name: SSH connection to Actions
        continue-on-error: true
        timeout-minutes: 340
        uses: P3TERX/ssh2actions@main
        with:
          mode: ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: us
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          LLVM_NAME: ${{ secrets.LLVM_NAME }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_EMAIL:  ${{ secrets.GH_EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_PUSH_REPO_URL: ${{ secrets.GH_PUSH_REPO_URL }}
